
model:
  name: simple_CNN

training:
  dataset: MNIST_Train

  max_epoch: 4
  batch_size: 16
  crop_size: None # [64, 64]
  aug: None # ['hflip', 'vflip', 'rot']

  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 1
      gamma: 0.1
  loss: 1.*cross_entropy
  optimizer:
    type: SGD
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: True
  warmup_iter: 1000

validation:
  val: True
  save_image: True
  save_file: True
  dataset: MNIST_Test
  batch_size: 16
  start_epoch: 16
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 500
  save_file: True
