
model_G: 
  type: ISPGAN_Generator
  kwargs:
    in_ch: 3
    out_ch: 3
model_D:
  type: CLtoN_D
  kwargs:
    n_ch_in: 3

trainer: Trainer_GAN

training:
  dataset:
    dataset_CL: prep_SIDD
    dataset_N : prep_SIDD
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: None # e.g.) None bypass stf_64-rnd
  crop_size: [160, 160]
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 1
  
  batch_size: 32

  max_epoch: 64
  
  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 16
      gamma: 0.32
  loss: 1.*LSGAN_D + 1.*LSGAN_G + 1e-2*zero_mean
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 200

validation:
  dataset: SIDD_val
  crop_size: None # [64, 64]
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: False
  n_data: 64

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10
  save_file: True

test:
  dataset: SIDD_val
  crop_size: None # [64, 64]
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # power_cliping: 2

  save_image: True