
model: DnCNN_B

model_input: masked # e.g.) real_noisy, syn_noisy, masked, clean

training:
  dataset: BSD400
  add_noise: gau-15. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: stf_64-rnd # e.g.) None bypass stf_64-rnd
  crop_size: [64, 64]
  aug: None # ['hflip', 'vflip', 'rot']
  n_repeat: 1
  
  batch_size: 16

  max_epoch: 12
  
  init_lr: 1e-3
  scheduler:
    type: step
    step:
      step_size: 10
      gamma: 0.1
  loss: 1.*L2
  optimizer:
    type: SGD
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: True
  warmup_iter: 100

validation:
  dataset: BSD68
  add_noise: gau-15. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: stf-64_rnd # e.g.) None stf-64_rnd
  crop_size: None # [64, 64]

  val: True
  save_image: True
  save_file: True
  
  start_epoch: 16
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 50
  save_file: True
