
model: 
  type: Laine19_Likelihood
  kwargs:
    in_ch: 3

model_input: [masked] # e.g.) real_noisy, syn_noisy, masked, clean

trainer: Trainer

training:
  dataset: Synthesized_CBSD68_25
  add_noise: None # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: bypass # e.g.) None bypass stf_0.7-rnd
  crop_size: [256, 256]
  #pixel_shuffle: 2
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 120
  
  batch_size: 4

  max_epoch: 100
  
  init_lr: 3e-4
  scheduler:
    type: step
    step:
      step_size: 40
      gamma: 0.1
  loss: 1.*self_Gau_likelihood + 0.001*neg_nlf_mean
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 100

validation:
  dataset: CBSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # multiple_cliping: 2

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 10
  interval_epoch: 10

log:
  interval_iter: 100

test:
  dataset: CBSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # multiple_cliping: 2

  save_image: True
