
model: 
  type: RBSN
  kwargs:
    in_ch: 3

model_input: [masked] # e.g.) real_noisy, syn_noisy, masked, clean

trainer: Trainer

training:
  dataset: DIV2K_train
  add_noise: gau-25. # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: bypass # e.g.) None bypass stf_0.7-rnd
  crop_size: [128, 128]
  #pixel_shuffle: 2
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 20
  
  batch_size: 16

  max_epoch: 64
  
  init_lr: 3e-4
  scheduler:
    type: step
    step:
      step_size: 16
      gamma: 0.32
  loss: 1*self_Gau_likelihood + 1e-1*self_L2 + 5e-2*neg_nlf_det + 1*n_var + 1*mu_var
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 200

validation:
  dataset: CBSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # multiple_cliping: 2

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10

test:
  dataset: CBSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # multiple_cliping: 2

  save_image: True
