
model: CDnCNN_B

model_input: masked # e.g.) real_noisy, syn_noisy, masked, clean

training:
  dataset: Synthesized_CBSD432_25
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: stf_1.0-rnd_2 # e.g.) None bypass stf_0.7-rnd
  crop_size: [256, 256]
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 1
  
  batch_size: 8

  max_epoch: 16
  
  init_lr: 1e-3
  scheduler:
    type: step
    step:
      step_size: 10
      gamma: 0.1
  loss: 1.*self_L1
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 100

validation:
  dataset: CBSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  power_cliping: 2

  val: True
  save_image: True
  save_file: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10
  save_file: True
