
model: DBSN

model_input: masked # e.g.) real_noisy, syn_noisy, masked, clean

training:
  #dataset: BSD432
  dataset: Synthesized_BSD432_25
  add_noise: None # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: bypass # e.g.) None bypass stf_0.7-rnd
  crop_size: [128, 128]
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 12
  
  batch_size: 16

  max_epoch: 200
  
  init_lr: 1e-3
  scheduler:
    type: step
    step:
      step_size: 50
      gamma: 0.3
  loss: 1.*self_L1
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 100

validation:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-25 # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # power_cliping: 2

  val: True
  save_image: True
  
  start_epoch: 10
  interval_epoch: 10
  
checkpoint:
  save: True
  start_epoch: 10
  interval_epoch: 10

log:
  interval_iter: 10

test:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-25 # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: False
  # power_cliping: 2

  save_image: True
