
model: N2V_UNet

model_input: [syn_noisy] # e.g.) real_noisy, syn_noisy, masked, clean

trainer: Trainer

training:
  dataset: BSD400
  add_noise: gau-15. # e.g.) None uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: None # e.g.) None bypass stf_64-rnd
  crop_size: [96, 96]
  aug: ['hflip', 'rot']
  normalization: True
  n_repeat: 10
  
  batch_size: 16

  max_epoch: 24
  
  init_lr: 1e-3
  scheduler:
    type: step
    step:
      step_size: 10
      gamma: 0.1
  loss: 1.*L2
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 100

validation:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-15. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: True
  multiple_cliping: 2

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 50

test:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-15. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: True
  multiple_cliping: 2

  save_image: True
