
model_G: 
  type: CLtoN_G_modified
  kwargs:
    n_ch_in: 3
    n_ch_out: 3
model_DN:
  type: CLtoN_D
  kwargs:
    n_ch_in: 3
model_DC:
  type: CLtoN_D
  kwargs:
    n_ch_in: 3
denoiser:
  type: DnCNN_B
  kwargs:
    in_ch: 3
    out_ch: 3

# model_input: syn_noisy # e.g.) real_noisy, syn_noisy, masked, clean

trainer: Trainer_GAN_E2E

training:
  dataset:
    dataset_CL: prep_SIDD
    dataset_N : prep_SIDD
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: None # e.g.) None bypass stf_64-rnd
  crop_size: [128, 128]
  aug: ['hflip', 'rot']
  normalization: True
  n_repeat: 1
  
  batch_size: 32

  max_epoch: 32
  
  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 8
      gamma: 0.32
  loss: 4.*DCGAN_D + 1.*DCGAN_G + 1e-2*L1 + 1e-2*batch_zero_mean
  optimizer:
    type: Adam
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: True
  warmup_iter: 200

validation:
  dataset: SIDD_val
  crop_size: None # [64, 64]
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: True
  n_data: 256

  val: True
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10
  save_file: True

test:
  dataset: SIDD_val
  crop_size: None # [64, 64]
  add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: bypass # e.g.) None bypass stf_64-rnd
  normalization: True
  # power_cliping: 2

  save_image: True