
model: 
  type: DnCNN_B
  kwargs:
    in_ch: 1
    out_ch: 1

model_input: [syn_noisy] # e.g.) real_noisy, syn_noisy, masked, clean

trainer: Trainer

training:
  dataset: BSD432
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
  mask: None # e.g.) None bypass stf_64-rnd
  crop_size: [64, 64]
  aug: ['hflip', 'rot']
  normalization: False
  n_repeat: 512
  
  batch_size: 128

  max_epoch: 50
  
  init_lr: 1e-2
  scheduler:
    type: step
    step:
      step_size: 20
      gamma: 0.1
  loss: 1.*L2
  optimizer:
    type: SGD
    SGD:
      momentum: 0.9
      weight_decay: 1e-4
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 100

validation:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: False

  val: True
  save_image: True
  
  start_epoch: 5
  interval_epoch: 5
  
checkpoint:
  save: True
  start_epoch: 5
  interval_epoch: 5

log:
  interval_iter: 50

test:
  dataset: BSD68
  crop_size: None # [64, 64]
  add_noise: gau-25. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
  mask: None # e.g.) None bypass stf_64-rnd
  normalization: False

  save_image: True
